# 1、首先：配置我当前服务器运行的 端口号
server:
  port: 9090


# 2、配置我的 DataSource -> 使用 Druid 数据源
  # 1. 注册驱动   2. 获取连接  3. 创建Statements模板对象  4. 执行SQL语句  5. 处理查询结果集  6. 释放资源
  # 但是这里我都不需要进行操作，全部由框架自动来帮我完成，springboot 中的自动装配技术是非常的强大的，大部分基本都可以自动化
  # 我们在这里充当的角色：我们只需要告诉框架boot 去哪里 去哪个数据库进行操作数据
  # --------------------------------------------------------------- #
  # 在以前 mybatis 项目中我的做的：
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 9834

# 3、配置我的 mybatis-plus 的信息 ： 我这里只配置了 日志输出问题
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl