# 配置项目路径问题和端口号
server:
  port: 9090
  servlet:
    context-path: /aop


# 配置数据库的信息
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 9834
